#
# Your Crowdin credentials
#
project_id: "449578"
api_token_env: CROWDIN_API_KEY
base_path: "."
base_url: "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
  {
    "source": "Masa-Family-Bucket-Translation-Pack/en_us/itemscroller.json",
    "translation": "Masa-Family-Bucket-Translation-Pack/%locale%/%original_file_name%",
  },
  {
    "source": "Masa-Family-Bucket-Translation-Pack/en_us/litematica.json",
    "translation": "Masa-Family-Bucket-Translation-Pack/%locale%/%original_file_name%",
  },
  {
    "source": "Masa-Family-Bucket-Translation-Pack/en_us/syncmatica.json",
    "translation": "Masa-Family-Bucket-Translation-Pack/%locale%/%original_file_name%",
  },
  {
    "source": "Masa-Family-Bucket-Translation-Pack/en_us/malilib.json",
    "translation": "Masa-Family-Bucket-Translation-Pack/%locale%/%original_file_name%",
  },
  {
    "source": "Masa-Family-Bucket-Translation-Pack/en_us/minihud.json",
    "translation": "Masa-Family-Bucket-Translation-Pack/%locale%/%original_file_name%",
  },
  {
    "source": "Masa-Family-Bucket-Translation-Pack/en_us/tweakeroo.json",
    "translation": "Masa-Family-Bucket-Translation-Pack/%locale%/%original_file_name%",
  }
]